CXD-61 Enrichment Migrator - Add regex matching option
atlanhq/atlan-java pull request #673
Opened 2024-05-30 06:30 UTC by ErnestoLoma

2024-06-04 17:24 UTC, cmgrote requested changes

2024-06-04 17:24 UTC, cmgrote commented on samples/packages/enrichment-migrator/src/main/kotlin/EnrichmentMigrator.kt
> +        targetConnectionQNs.forEachIndexed { _, targetConnectionQN ->
Since we're not using the index anyway, should just replace `forEachIndexed` with `forEach` and drop the first arg altogether.

2024-06-04 17:24 UTC, cmgrote commented on samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/AssetTransformer.kt
> +        System.out.println(inputRow)
Remove these debugging print statements

2024-06-05 05:52 UTC, ErnestoLoma commented on samples/packages/enrichment-migrator/src/main/kotlin/EnrichmentMigrator.kt
> +            if (databaseNames.size < 1) {
Done

2024-06-05 05:52 UTC, ErnestoLoma commented on samples/packages/enrichment-migrator/src/main/kotlin/EnrichmentMigrator.kt
> +    fun getDatabaseNames(connectionQN: String, sourcePrefix: String): MutableList<String> {
Done

2024-06-05 08:25 UTC, ErnestoLoma commented on samples/packages/enrichment-migrator/src/main/kotlin/EnrichmentMigrator.kt
> +                    assetsFailOnErrors = Utils.getOrDefault(config.failOnErrors, true),
I'm missing something. The extract is only occurring once since it's outside the loop.

2024-06-05 09:34 UTC, cmgrote commented on samples/packages/enrichment-migrator/src/main/kotlin/EnrichmentMigrator.kt
> +                    assetsFailOnErrors = Utils.getOrDefault(config.failOnErrors, true),
Sorry, by extract I mean — `Utils.getOrDefault(config.failOnErrors, true)` <— is happening potentially many times

2024-06-05 09:57 UTC, ErnestoLoma commented on samples/packages/enrichment-migrator/src/main/kotlin/Transformer.kt
> +                raw.replace(ctx.sourceConnectionQN, ctx.targetConnectionQN).replace(ctx.sourceDatabaseName, ctx.targetDatabaseName)
Something like this @cmgrote

2024-06-05 09:57 UTC, ErnestoLoma commented on samples/packages/enrichment-migrator/src/main/kotlin/Transformer.kt
> +                val regex = "(^|[/])${ctx.sourceDatabaseName}($|[/])".toRegex()
Something like this @cmgrote ?

2024-06-05 09:57 UTC, ErnestoLoma commented on samples/packages/enrichment-migrator/src/test/kotlin/EnrichmentMigratorPatternTest.kt
> +    }
Done

2024-06-05 09:57 UTC, ErnestoLoma commented on samples/packages/lineage-builder/src/main/kotlin/com/atlan/pkg/lb/AssetTransformer.kt
> +        System.out.println(inputRow)
done.

2024-06-05 10:05 UTC, ErnestoLoma commented on samples/packages/enrichment-migrator/src/main/kotlin/EnrichmentMigrator.kt
> +                    assetsFailOnErrors = Utils.getOrDefault(config.failOnErrors, true),
Done

2024-06-05 16:05 UTC, cmgrote approved these changes

2024-06-06 06:01 UTC, merged